@url = https://8080-amaranth-python-bap6kgak.ws-us17.gitpod.io/filmes
 
GET {{url}}/filmes
POST {{url}}/filmes
Content-Type: application/json

{
    "titulo" : "exemplo"
}
 
PUT {{url}}/filmes/4
 Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}

DELETE {{url}}/filmes
Content-Type: application/json

{
    "id" : "4"
}
